services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    environment:
      ND_ENABLEINSIGHTSCOLLECTOR: false
    ports:
      - ${PORT}:4533
    networks: [global]
    restart: unless-stopped
    volumes:
      - /persist/navidrome:/data
      - /cache/navidrome:/data/cache
      - ${MUSIC_LOCATION}:/music:ro

networks:
  global:
    external: true
