services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    environment:
      DATABASE_URL: postgres://user:pass@outline_postgres:5432/outline
      PGSSLMODE: disable
      REDIS_URL: redis://outline_redis:6379
      REDIS_COLLABORATION_URL: redis://outline_redis:6379
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      URL: https://outline.phr0gw0rld.com
      COLLABORATION_URL: https://outline.phr0gw0rld.com
    ports:
      - 3002:3000
    expose:
      - 3000
    volumes:
      - /persist/outline:/var/lib/outline/data
    networks:
      - proxy
      - internal
    depends_on:
      - outline_postgres
      - outline_redis

  outline_redis:
    container_name: outline_redis
    image: redis
    volumes:
      - ./redis.conf:/redis.conf
    networks:
      - internal
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  outline_postgres:
    container_name: outline_postgres
    image: postgres:18
    volumes:
      - /persist/outline/postgres:/var/lib/postgresql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

networks:
  proxy:
    external: true
  internal:
    driver: bridge
