services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    user: 1000:1000
    environment:
      TZ: Australia/Melbourne
    ports:
      - '9090:9090'
    networks:
      - global
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /persist/prometheus:/prometheus

networks:
  global:
    external: true
