#!/bin/python3
import yaml
import os

dockerPath = f"/docker"
separator = "--"
cloudflareFile = f"/etc/cloudflared/config.yml"
tunnelID = "60ad33ce-3351-49a9-b750-2e25951e76d5"
tunnelKey = f"/etc/cloudflared/{tunnelID}.json"
subdomains = []

# load file
with open(f"{dockerPath}/env.yml", "r") as file:
    data = yaml.safe_load(file)


# sort memory
data = dict(sorted(data.items()))

# get meta data
meta = data.pop("_meta")

def has_prefix(name: str) -> bool:
    return len(name.split(separator))== 2

def get_prefix(name: str) -> str:
    return name.split(separator)[0]

def get_postfix(name: str) -> str:
    return name.split(separator)[1]

ports = set()
samePortWarn = "the following services have repeated ports:\n"


cloudflareConfig =  "# This file was generated by ~/docker/genenv.py\n"
cloudflareConfig += f"tunnel: {tunnelID}\n"
cloudflareConfig += f"credentials-file: {tunnelKey}\n"
cloudflareConfig += "ingress:\n"

for serviceName, serviceMeta in data.items():
    print(f"Updating {serviceName}...")
    # set port
    port = serviceMeta["PORT"]
    print(f"  Port: {port}")
    envContents = f"PORT=\"{port}\"\n"

    # same port check
    if port in ports:
        samePortWarn += f"\n{serviceName}"
        print("  warn: duplicate port")
    ports.add(port)

    # generate .env
    if "env" in serviceMeta:
        for varName, varValue in serviceMeta["env"].items():
            print(f"  Setting {varName}")
            if varValue is True:
                varValue = "true"
            elif varValue is False:
                varValue = "false"
            envContents += f"{varName}=\"{varValue}\"\n"

    # generate prefix based
    if has_prefix(serviceName):
        if get_prefix(serviceName) in meta.keys():
            for varName, varValue in meta[get_prefix(serviceName)].items():
                envContents += f"{varName}=\"{str(varValue)}\"\n"

    
    # write .env
    with open(f"{dockerPath}/{serviceName}/.env", "w") as f:
        f.write(envContents)

    # cloudflare stuff
    if not has_prefix(serviceName):
        print("  Configuring Cloudflare")
        subdomain = serviceName
        protocol = "http"
        if "subdomain" in serviceMeta.keys():
            subdomain = serviceMeta["subdomain"]
        if "protocol" in serviceMeta.keys():
            protocol = serviceMeta["protocol"]
        print(f"    subdomain: {subdomain}")
        print(f"    protocol: {protocol}")

        # generate cloudflare rules
        hostname = f"{subdomain}.phr0gw0rld.com"
        ingressrule =  f"""
# Rule for {serviceName}\n
  - hostname: {hostname}
    service: {protocol}://localhost:{port}
"""
        if protocol == "https":
            ingressrule+= f"""
    originRequest:
      httpHostHeader: {hostname}
      disableChunkedEncoding: true
      noTLSVerify: true
      headers:
        X-Forwarded-Proto: https
        X-Forwarded-For: $CF-Connecting-IP
        X-Real-IP: $CF-Connecting-IP

"""
        cloudflareConfig += ingressrule
        subdomains.append(subdomain)

    # finish it all
    print(f"Successfully updated {serviceName}\n")
print("All services updated\n")

# push to cloudflare config
cloudflareConfig += f"\n# Catch all rule\n"
cloudflareConfig += f"  - service: http_status:404\n"
print(f"\nGenerating cloudflare config at {cloudflareFile}")
os.system(f"touch {cloudflareFile}")
with open(cloudflareFile, "w") as f:
    f.write(cloudflareConfig)
print("Generated config")
print("Restarting cloudflared")
os.system("sudo systemctl restart cloudflared")

